version: '3'
services:

  php:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www
    links:
      - mysql_db

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php    

  mysql_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 6033:3306
    volumes:
      - ./docker/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1